OSKON/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^vyrobni_program/', include('vyrobni_program.urls')),
    url(r'', include('o_nas.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

o_nas/urls.py
from django.conf.urls import url

from . import views

app_name = 'o_nas'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^kontakt/$', views.kontakt, name='kontakt'),
    url(r'^galerie/$', views.galerie, name='galerie'),
    url(r'^reference/$', views.reference, name='reference'),
]

vyrobni_program/urls.py
from django.conf.urls import url

from . import views

app_name = 'vyrobni_program'
urlpatterns = [
    url(r'^$', views.index, name='vyrobni_program'),
    url(r'^(?P<category_id>[0-9]+)/$', views.detail, name='detail'),
]

form/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    subject = models.CharField(max_length=200, null=True)
    message = models.TextField(null=True)
    email = models.EmailField(null=True)
    telefon = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.subject

o_nas/models.py
from django.db import models

class Gallery(models.Model):
    name = models.CharField(max_length=128, unique=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    pub_date = models.DateTimeField('date published', null=True, blank=True)

    def __str__(self):
        return str(self.name)

class Reference(models.Model):
    name = models.CharField(max_length=128, unique=True, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    link = models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.name

vyrobni_program/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.encoding import python_2_unicode_compatible


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    short_description = models.CharField(max_length=250, null=True, blank=True)
    pub_date = models.DateTimeField('date published', null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    long_description = RichTextField(max_length=5000, null=True, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    image = models.ImageField()
    description2 = models.CharField(max_length=5000, null=True, blank=True)

    def __str__(self):
        return self.title

class Picture(models.Model):
    name = models.CharField(max_length=150, null=True, blank=True, unique=True)
    picture = models.ImageField(null=True, blank=True)
    category = models.ForeignKey(Category)
    pub_date = models.DateTimeField('date published', null=True, blank=True)
    popis = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.name)

form/forms.py
from django import forms


from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            "subject",
            "message",
            "email",
            "telefon",
        ]

form/views.py
from django.shortcuts import render

# Create your views here.

o_nas/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Gallery, Reference
from form.models import Contact
from form.forms import ContactForm
from django.contrib import messages

def index(request):
    template = loader.get_template('o_nas/index.html')
    context = {}
    return render(request, 'o_nas/index.html', context)

def kontakt(request):
    template = loader.get_template('o_nas/kontakt.html')
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            messages.success(request, 'Thank you for your message.')
            return HttpResponseRedirect('/kontakt/')
    else:
        form = ContactForm()
    context = {'form':form}
    return render(request, 'o_nas/kontakt.html', context)





def galerie(request):
    list_of_images = Gallery.objects.order_by('-pub_date')
    template=loader.get_template('o_nas/galerie.html')
    context = {'list_of_images': list_of_images}
    return render(request, 'o_nas/galerie.html', context)

def reference(request):
    list_of_references = Reference.objects.order_by('-pub_date')
    template=loader.get_template('o_nas/reference.html')
    context = {"list_of_references": list_of_references}
    return render(request, 'o_nas/reference.html', context)

vyrobni_program/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Product, Category, Picture
from django.template import loader



def index(request):
    list_of_categories = Category.objects.order_by('-pub_date')[:27]
    template = loader.get_template('vyrobni_program/vyrobni_program.html')
    context = {'list_of_categories': list_of_categories}
    return render(request, 'vyrobni_program/vyrobni_program.html', context)



def detail(request, category_id):
    try:
        category = Category.objects.get(pk=category_id)
        listofpictures = Picture.objects.filter(category_id=category_id)

    except Category.DoesNotExist:
        raise Http404('Category does not exist')
    return render(request, 'vyrobni_program/detail.html',
    {'category': category,
    'listofpictures': listofpictures})

o_nas/templates/o_nas/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta  charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "vyrobni_program/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "vyrobni_program/css/style.css" %}">
    <link rel="stylesheet" href="{% static "vyrobni_program/css/font-awesome.min.css" %}">

    <title>OSKON</title>
</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsemenu" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>

    </button>
    <div class="navbar-brand"> <a href="{% url 'o_nas:index' %}"><img id="brand" src="/media/logo (2).png"></a>


    </div>
    <div class="collapse navbar-collapse" id="collapsemenu">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'o_nas:index' %}">Úvod</a></li>

        </li>
          <li><a class="color" href="{% url 'vyrobni_program:vyrobni_program' %}">Výrobni program</a></li>
          <li><a href="{% url 'o_nas:galerie' %}">Galerie</a></li>
          <li><a href="{% url 'o_nas:reference' %}">Reference</a></li>
          <li><a href="{% url 'o_nas:kontakt' %}">Kontakt</a></li>

        </ul>

    </div>

  </div>
  </nav>

  {% block content %}
  {% endblock %}












<footer>
    <div class="container">
      <p>
        OSKON s.r.o. 2016
      </p>
    </div>
</footer>
<script src="{% static "vyrobni_program/js/jquery-3.1.0.min.js" %}"></script>
<script src="{% static "vyrobni_program/js/bootstrap.min.js" %}"></script>
<script src="{% static "vyrobni_program/js/script.js" %}"></script>
</body>

</html>

o_nas/templates/o_nas/galerie.html
{% extends 'o_nas/base.html' %}

{% block content %}
<div class="container" style="margin-top:1cm">
  <h3>Ukazka nasich produktu:</h3>
  <hr style="margin-bottom: 1cm">
  <div class="row">
    {% for i in list_of_images %}
      <div class="col-sm-6 col-md-4" style="margin-bottom: 20px">

        <a href="#">
          <img class="myImg img-responsive img-hover" style="height: 200px; width: 356px" src="{{ i.image.url }}">
        </a>

        <div id="Fullscreen">
          <img src="" alt="" />
        </div>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

o_nas/templates/o_nas/index.html
{% extends 'o_nas/base.html' %}

{% block content %}
<div class="content container">
  <div class="row">
    <section class="col-sm-12">
      <div class="carousel slide" id="featured">
        <ol class="carousel-indicators">
          <li data-target="#featured" data-slide-to="0" class="active"></li>
          <li data-target="#featured" data-slide-to="1"></li>
          <li data-target="#featured" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="item active">
            <img src="media/carousel1.jpg">
            <div class="carousel-caption">
              <h3>Obrábění</h3>


            </div>
          </div>
          <div class="item">
            <img src="media/5ir6oKY.png">
            <div class="carousel-caption">
              <h3>Konstrukce</h3>


            </div>
          </div>
          <div class="item">
            <img src="media/carousel2.jpg">
            <div class="carousel-caption">
              <h3>Svařování</h3>

            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#featured" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="right carousel-control" href="#featured" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
      </section>
    </div>
  </div>
</div>

<div class="container" style="margin-top:1cm">
  <div class="col-lg-12">
      <h1>
          Welcome to Oskon website
      </h1>
      <p>Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean sit amet
      luctus ligula.Proin eros augue, pharetra quis eros ac, dignissim tempus felis.Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean sit amet
      luctus ligula.Proin eros augue, pharetra quis eros ac, dignissim tempus felis.Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean sit amet
      luctus ligula.Proin eros augue, pharetra quis eros ac, dignissim tempus felis.</p>
      <hr>
  </div>
  <div class="row">


    <div class="col-xs-12 col-sm-4">
        <div class="panel panel-default">
          <div class="panel-heading">
                <a href="{% url 'vyrobni_program:vyrobni_program'%}"><h4>Výrobni program</h4></a>
          </div>
          <div class="panel-body">
                <p>
                  Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean sit amet
                  luctus ligula.Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean
                </p>
                <a class="btn btn-default" href="{% url 'vyrobni_program:vyrobni_program'%}">Vice informací</a>
          </div>

          </div>
        </div>
      <div class="col-xs-12 col-sm-4">
          <div class="panel panel-default">
            <div class="panel-heading">
                  <a href="{% url 'o_nas:kontakt'%}"><h4>Kontakt</h4></a>
            </div>
            <div class="panel-body">
                  <p>
                    Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean sit amet
                    luctus ligula.Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean
                  </p>
                  <a class="btn btn-default" href="{% url 'o_nas:kontakt'%}">Vice informací</a>
            </div>

            </div>
          </div>




              <div class="col-xs-12 col-sm-4">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                          <a href="{% url 'o_nas:galerie'%}"><h4>Galerie</h4></a>
                    </div>
                    <div class="panel-body">
                          <p>
                            Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean sit amet
                            luctus ligula.Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean
                          </p>
                          <a class="btn btn-default" href="{% url 'o_nas:galerie'%}">Vice informací</a>
                    </div>

                    </div>
                  </div>

</div>







  </div>
</div>

{% endblock %}

o_nas/templates/o_nas/kontakt.html
{% extends 'o_nas/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
<div class="container">
  <div class="row">
  <div class="col-sm-12 col-md-12">
    <div class="page-header" style="margin-bottom:1cm">
      <h1>Kontaktujte nas</h1>
      <p>
      Quisque quam ex, aliquam id ligula aliquet, mollis sodales eros. Duis eros ante, interdum in odio ac, fringilla dignissim nisl.
      Aliquam tempor at quam nec laoreet. Curabitur libero massa, mollis et nunc in, placerat suscipit dui. Ut a convallis felis.
      Phasellus pellentesque metus sed dui posuere lobortis. Aliquam ultrices porta velit, in pulvinar ante finibus vitae.
      Suspendisse semper fermentum lectus at sagittis. Proin placerat quis eros nec faucibus. Morbi gravida ligula laoreet,
      fringilla velit in, pulvinar purus. Proin eros augue, pharetra quis eros ac, dignissim tempus felis. Aenean sit amet
      luctus ligula.</p>
    </div>

  </div>
  </div>
</div>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} style="color:#00ff00" class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="container">
  <div class="row" style="margin-bottom:1cm">
    <div class="col-md-6" style="margin-bottom: 20px">
      <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Submit" />
      </form>
    </div>

    <div class="col-md-6" style="margin-bottom: 20px">
      <div class="thumbail">
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBiOnDSgDcIcwGjmVAyMZxRUtx6hUPOQf0">
        </script><div class="thumbnail" style='overflow:hidden;height:502px;max-width: auto;'>
          <div id='gmap_canvas' style='height:502px;max-width: auto;'></div><div><small>
            <a href="http://www.embedgooglemaps.com">Generate your Google map here, quick and easy!</a>
          </small></div><div><small>
            <a href="https://top10geeks.com/top-10-best-running-shoes-men-2016/">
              With top10geeks.com, you can read everything about the best running shoes for men for the year 2016.
              We give insights in what is the best shoe to buy, by looking at it's qualities and value for money.
              However, it is important that you always try the shoe for yourself: you might have different preferences
              than what we are recommending. With our tips of the best running shoes for men, you cannot go wrong!</a>
            </small></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style>
          </div><script type='text/javascript'>function init_map(){
            var myOptions = {zoom:13,center:new google.maps.LatLng(50.10671223402563,14.401405037109392),
              mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'),
              myOptions);marker = new google.maps.Marker({
                map: map,position: new google.maps.LatLng(50.10671223402563,14.401405037109392)});
                infowindow = new google.maps.InfoWindow({
                  content:'<strong>mapa</strong><br>czech republic, prague, Technická 4, 166 07<br>'});
                  google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});
                  infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>

      </div>

    </div>
  </div>
</div>


  <div class="container">
    <div class="row">
      <div  style="padding: 0px">
        <table class="table table-hover">
          <tbody>
            <tr>
              <th scope="row">
                Nazev Spolecnosti
              </th>
              <td>
                OSKON s.r.o.
              </td>
            </tr>
            <tr>
              <th scope="row">
                Sidlo
              </th>
              <td>
                Quisque quam ex, aliquam id ligula aliquet, mollis sodales eros. Duis eros ante, interdum in odio ac, fringilla dignissim nisl.
              </td>
            </tr>
            <tr>
              <th scope="row">
                Provozovna
              </th>
              <td>
                Quisque quam ex, aliquam id ligula aliquet, mollis sodales eros. Duis eros ante, interdum in odio ac, fringilla dignissim nisl.
              </td>
            </tr>
            <tr>
              <th scope="row">
                ICO
              </th>
              <td>
                45456 456456 4564156
              </td>
            </tr>
            <tr>
              <th scope="row">
                DIC
              </th>
              <td>
                45456 456456 4564156
              </td>
            </tr>
            <tr>
              <th scope="row">
                Telefon
              </th>
              <td>
                45456 456456 4564156
              </td>
          </tbody>
        </table>
      </div>
    </div>
  </div>

</div>

{% endblock %}

o_nas/templates/o_nas/reference.html
{% extends 'o_nas/base.html' %}

{% block content %}

<div class="container" style="padding-top: 1cm">
  <h3>Nasi odberatele:</h3>
  <hr >
    <div class="row" >

      {% if list_of_references %}
          {% for reference in list_of_references %}
          <div class="col-md-4 col-sm-6" style="margin-bottom:20px">
          <div class="media">
              <div class="pull-left">
                  <span>
                        <a href="{{ reference.link }}"><img style="height: 60px; width:60px" src="{{ reference.image.url }}"></a>
                  </span>
              </div>
              <div class="media-body">
                  <a href="{{ reference.link }}"><h4 class="media-heading">{{ reference.name }}</h4></a>
                  <p>{{ reference.description }}</p>
              </div>
          </div>
          </div>
          {% endfor %}

      {% else %}
          <p>No references are available.</p>
      {% endif %}


    </div>
    </div>

{% endblock %}

vyrobni_program/templates/vyrobni_program/detail.html
{% extends 'o_nas/base.html' %}

{% block content %}

  <div class="container">
    <div class="row">


          <h2>{{ category.name }}</h2>

        <div>
          {{ category.long_description|safe }}
        </div>
      </div>
    </div>

    <div class="container">
      {% for picture in listofpictures %}
      <div class="row" style="margin-bottom:1cm">

          <div class="col-md-7">
                <img class="img-responsive" style="width:700px; height: 300px" src="{{ picture.picture.url }}">


          </div>
          <div class="col-md-5">
                <h3>{{ picture.name }}</h3>

                <p>{{ picture.popis }}</p>

          </div>

      </div>
      {% endfor %}
    </div>
  {% endblock %}

  <!--
  <div class="row">
      <div class="col-md-7">
          <a href="portfolio-item.html">
              <img class="img-responsive img-hover" src="http://placehold.it/700x300" alt="">
          </a>
      </div>
      <div class="col-md-5">
          <h3>Project One</h3>
          <h4>Subheading</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
          <a class="btn btn-primary" href="portfolio-item.html">View Project</i></a>
      </div>
  </div>
  -->

vyrobni_program/templates/vyrobni_program/vyrobni_program.html
{% extends 'o_nas/base.html' %}

{% block content %}

<div class="container" style="margin-top: 1cm">
  <h3>Kategorie vyroby:</h3>
  <hr>
    <div class="row">

    {% if list_of_categories %}
        {% for category in list_of_categories %}
        <div class="col-lg-4  col-md-4 col-sm-6 col-xs-12" style="margin-bottom:20px">

        <a href="{% url 'vyrobni_program:detail' category.id %}"><img class="img-responsive" src="{{ category.image.url }}"></a>

  						<h3><a href="{% url 'vyrobni_program:detail' category.id %}">{{ category.name }}</a></h3>
  						<p>{{ category.short_description }}</p>

  							<a class="btn btn-default btn-xs" href="{% url 'vyrobni_program:detail' category.id %}">Vice informaci</a>


        </div>
        {% endfor %}

    {% else %}
        <p>No categories are available.</p>
    {% endif %}

    </div>
    </div>
{% endblock %}